name: Hello Selfhosted Runner
on:
  push:
    branches:
      - main  # 実行したいブランチを指定

jobs:
  hello:
    name: Hello
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Hello
      run: bash hello.sh
